import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, Check, ChevronLeft, Plus, RotateCcw, Sparkles, Trash2, Users, Zap } from 'lucide-react';
import './styles.css';
import type { Context, Member, TeamInput } from './types';
import { analyzeTeam } from './lib/analyzeTeam';

const contexts: [Context, string, string][] = [['kickoff','🚀','프로젝트 킥오프'],['ideation','💡','아이디어 회의'],['execution','✅','실행 중심 업무'],['conflict','🫶','갈등 조정'],['daily','☕','일상 협업']];
const mbtis = ['ISTJ','ISFJ','INFJ','INTJ','ISTP','ISFP','INFP','INTP','ESTP','ESFP','ENFP','ENTP','ESTJ','ESFJ','ENFJ','ENTJ'];
const initial = (): Member => ({ id: crypto.randomUUID(), name: '', mbti: '' });

function App() {
  const [step, setStep] = useState(0); const [team, setTeam] = useState<TeamInput>({ teamName:'', goal:'', context:'ideation', members:[initial(), initial()] }); const [result, setResult] = useState<ReturnType<typeof analyzeTeam> | null>(null);
  const update = (key: keyof TeamInput, value: string) => setTeam(t => ({ ...t, [key]: value } as TeamInput));
  const updateMember = (id: string, key: keyof Member, value: string) => setTeam(t => ({ ...t, members:t.members.map(m => m.id===id ? {...m, [key]:value}:m) }));
  const canAnalyze = team.teamName.trim() && team.members.length >= 2 && team.members.every(m => m.name.trim() && m.mbti);
  if (step === 0) return <main className="landing"><div className="orb orb-a"/><div className="orb orb-b"/><nav><div className="logo"><span>MBTI</span> 팀 케미</div><span className="nav-note">Team vibe, decoded.</span></nav><section className="hero"><div className="eyebrow"><Sparkles size={15}/> SCENARIO 13. TEAM VIBE</div><h1>우리 팀의 케미,<br/><em>데이터로</em> 알아볼까요?</h1><p>팀원의 MBTI를 입력하면 팀 전체의 강점과 갈등 포인트,<br/>더 잘 협업하는 방법까지 한눈에 분석해 드려요.</p><button className="primary" onClick={() => setStep(1)}>팀 분석 시작하기 <ArrowRight size={18}/></button><div className="trust"><Users size={15}/> 팀원 최대 10명 · 약 2분 소요</div></section><div className="landing-foot"><span>MBTI TEAM CHEMISTRY ANALYZER</span><span>참고용 협업 도구</span></div></main>;
  if (step === 1) return <div className="app-shell"><Header step={1}/><section className="form-page"><button className="back" onClick={() => setStep(0)}><ChevronLeft size={16}/> 처음으로</button><div className="page-title"><div className="eyebrow">STEP 01 · TEAM SETUP</div><h2>어떤 팀인지 알려주세요</h2><p>팀의 상황을 알면 더 실용적인 협업 팁을 드릴 수 있어요.</p></div><div className="form-grid"><label>팀 이름<input placeholder="예: 마케팅 2팀" value={team.teamName} onChange={e=>update('teamName',e.target.value)}/></label><label>프로젝트 목표<input placeholder="예: 신규 캠페인 아이디어 발굴" value={team.goal} onChange={e=>update('goal',e.target.value)}/></label></div><div className="field-block"><h3>지금 가장 가까운 협업 상황</h3><div className="context-grid">{contexts.map(([id,icon,label])=><button key={id} className={team.context===id?'context active':'context'} onClick={()=>update('context',id)}><span>{icon}</span>{label}{team.context===id&&<Check size={15}/>}</button>)}</div></div><div className="field-block"><div className="section-head"><h3>팀원을 추가해주세요 <small>{team.members.length}/10</small></h3>{team.members.length<10&&<button className="add" onClick={()=>setTeam(t=>({...t,members:[...t.members,initial()]}))}><Plus size={16}/> 팀원 추가</button>}</div><div className="members">{team.members.map((m,i)=><div className="member-row" key={m.id}><span className="number">{String(i+1).padStart(2,'0')}</span><input placeholder="이름" value={m.name} onChange={e=>updateMember(m.id,'name',e.target.value)}/><select value={m.mbti} onChange={e=>updateMember(m.id,'mbti',e.target.value)}><option value="">MBTI 선택</option>{mbtis.map(x=><option key={x}>{x}</option>)}</select>{team.members.length>2&&<button className="icon-button" onClick={()=>setTeam(t=>({...t,members:t.members.filter(x=>x.id!==m.id)}))}><Trash2 size={16}/></button>}</div>)}</div></div><button className="primary wide" disabled={!canAnalyze} onClick={()=>{setResult(analyzeTeam(team));setStep(2)}}>우리 팀 분석하기 <Zap size={17}/></button></section></div>;
  return <Result result={result!} team={team} onReset={()=>{setResult(null);setStep(1)}}/>;
}
function Header({step}:{step:number}) { return <header className="header"><div className="logo"><span>MBTI</span> 팀 케미</div><div className="progress"><i className="on"/><i className={step>=1?'on':''}/><i className={step>=2?'on':''}/></div><span className="step-label">{step===1?'정보 입력':'분석 결과'}</span></header> }
function Result({result,team,onReset}:{result:ReturnType<typeof analyzeTeam>;team:TeamInput;onReset:()=>void}) { return <div className="app-shell"><Header step={2}/><main className="result-page"><div className="result-hero"><div><div className="eyebrow"><Sparkles size={15}/> ANALYSIS COMPLETE</div><h2>{team.teamName}의 팀 케미 리포트</h2><p>{result.summary}</p></div><div className="score"><strong>{result.score}</strong><span>/ 100</span><small>TEAM VIBE SCORE</small></div></div><div className="notice">ⓘ 케미 점수는 MBTI 조합과 협업 상황을 바탕으로 계산한 참고용 지표예요. 사람의 역량이나 적합도를 판단하는 기준이 아닙니다.</div><section className="dashboard-grid"><article className="card profile-card"><div className="card-title"><span className="card-icon purple"><Users size={18}/></span><div><h3>팀 성향 밸런스</h3><p>우리 팀은 어떤 방식으로 움직일까요?</p></div></div>{[['E','I'],['S','N'],['T','F'],['J','P']].map(([a,b])=><div className="bar-row" key={a}><span>{a}</span><div className="bar"><i style={{width:`${result.profile[a]}%`}}/><b style={{left:`${result.profile[a]}%`}}/></div><span>{b}</span><small>{result.profile[a]} : {result.profile[b]}</small></div>)}</article><article className="card"><div className="card-title"><span className="card-icon yellow"><Sparkles size={18}/></span><div><h3>우리 팀의 강점</h3><p>성향이 만나 만들어내는 시너지</p></div></div><div className="strengths">{result.strengths.map(s=><div className="mini-card" key={s.letter}><b>{s.title}</b><p>{s.text}</p><em>{s.letter} 성향 기반</em></div>)}</div></article></section><section className="section-heading"><div><div className="eyebrow">TEAM PLAYBOOK</div><h2>같이 일할 때 더 좋아지는 방법</h2></div><button className="outline" onClick={onReset}><RotateCcw size={15}/> 다시 분석하기</button></section><section className="dashboard-grid lower"><article className="card"><div className="card-title"><span className="card-icon pink"><Zap size={18}/></span><div><h3>잠재 갈등 포인트</h3><p>미리 알면 가볍게 넘길 수 있어요</p></div></div>{result.conflicts.length ? result.conflicts.map(c=><div className="conflict" key={c.title}><b>{c.title}</b><p>{c.text}</p><small>TIP · {c.tip}</small></div>):<div className="empty">서로 다른 관점이 잘 섞여 있어요. 의견을 내기 전 기준만 합의해 보세요.</div>}</article><article className="card"><div className="card-title"><span className="card-icon blue"><Users size={18}/></span><div><h3>팀원별 추천 역할</h3><p>상황에 따라 유연하게 바꿔보세요</p></div></div><div className="roles">{result.roles.map(r=><div className="role" key={r.member.id}><span>{r.role.icon}</span><div><b>{r.member.name}</b><small>{r.member.mbti} · {r.role.name}</small></div></div>)}</div></article></section><div className="collab-tip"><div className="tip-mark">“</div><div><b>이번 협업을 위한 한 가지 약속</b><p>회의에서는 먼저 각자 3분 동안 생각을 정리하고, 그 다음 자유롭게 아이디어를 나눠보세요. 서로 다른 속도가 팀의 깊이를 만들어요.</p></div></div></main></div> }
createRoot(document.getElementById('root')!).render(<App />);
